// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_queries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthUserByGithubID = `-- name: GetAuthUserByGithubID :one
SELECT id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at FROM auth_users WHERE github_id = $1
`

func (q *Queries) GetAuthUserByGithubID(ctx context.Context, githubID string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByGithubID, githubID)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at FROM auth_users WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getAuthUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at FROM refresh_tokens
WHERE token_hash = $1
  AND revoked = false
  AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked = true WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = true WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, tokenHash)
	return err
}

const upsertAuthUser = `-- name: UpsertAuthUser :one
INSERT INTO auth_users (id, github_id, username, email, avatar_url, last_login_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (github_id) DO UPDATE
    SET username      = EXCLUDED.username,
        email         = EXCLUDED.email,
        avatar_url    = EXCLUDED.avatar_url,
        last_login_at = NOW()
RETURNING id, github_id, username, email, avatar_url, role, is_active, last_login_at, created_at
`

type UpsertAuthUserParams struct {
	ID        uuid.UUID
	GithubID  string
	Username  string
	Email     string
	AvatarUrl string
}

func (q *Queries) UpsertAuthUser(ctx context.Context, arg UpsertAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, upsertAuthUser,
		arg.ID,
		arg.GithubID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
