// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthUser struct {
	ID          uuid.UUID
	GithubID    string
	Username    string
	Email       string
	AvatarUrl   string
	Role        string
	IsActive    bool
	LastLoginAt sql.NullTime
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	Revoked   bool
	CreatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Name               string
	Gender             string
	GenderProbability  float64
	Age                int32
	CountryName        string
	AgeGroup           string
	CountryID          string
	CountryProbability float64
	CreatedAt          sql.NullString
}
