// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO users(id, name, gender, gender_probability, age,age_group, country_id, country_probability, created_at )
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW()
)RETURNING id, name, gender, gender_probability, age, country_name, age_group, country_id, country_probability, created_at
`

type CreateProfileParams struct {
	ID                 uuid.UUID
	Name               string
	Gender             string
	GenderProbability  float64
	Age                int32
	AgeGroup           string
	CountryID          string
	CountryProbability float64
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.GenderProbability,
		arg.Age,
		arg.AgeGroup,
		arg.CountryID,
		arg.CountryProbability,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.CountryName,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfileByID = `-- name: DeleteProfileByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteProfileByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileByID, id)
	return err
}

const getAllProfiles = `-- name: GetAllProfiles :many
SELECT id, name, gender, gender_probability, age, country_name, age_group, country_id, country_probability, created_at FROM users
`

func (q *Queries) GetAllProfiles(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.GenderProbability,
			&i.Age,
			&i.CountryName,
			&i.AgeGroup,
			&i.CountryID,
			&i.CountryProbability,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, name, gender, gender_probability, age, country_name, age_group, country_id, country_probability, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.CountryName,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
 SELECT id, name, gender, gender_probability, age, country_name, age_group, country_id, country_probability, created_at FROM users
WHERE name = $1
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getProfileByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.GenderProbability,
		&i.Age,
		&i.CountryName,
		&i.AgeGroup,
		&i.CountryID,
		&i.CountryProbability,
		&i.CreatedAt,
	)
	return i, err
}
